// components/ui/Checkbox.vue
<script setup lang="ts">
import { computed } from 'vue'
import { cn } from '../utils/cn'

const props = withDefaults(
  defineProps<{
    modelValue?: boolean
    disabled?: boolean
    className?: string
    id?: string
  }>(),
  { modelValue: false }
)

const emit = defineEmits<{ 'update:modelValue': [boolean] }>()

const checked = computed({
  get: () => props.modelValue,
  set: (value: boolean) => emit('update:modelValue', value),
})
</script>

<template>
  <label class="inline-flex items-center gap-2">
    <input
      :id="props.id"
      v-model="checked"
      type="checkbox"
      :disabled="props.disabled"
      :class="cn('h-4 w-4 rounded border-stone-300 text-primary focus:ring-1 focus:ring-primary disabled:opacity-50 disabled:cursor-not-allowed', props.className)"
    />
    <slot />
  </label>
</template>

// src/components/ui/checkbox.tsx
"use client"

import * as React from "react"
import * as CheckboxPrimitive from "@radix-ui/react-checkbox"
import { CheckIcon } from "@radix-ui/react-icons"

import { cn } from "@/lib/utils"

const Checkbox = React.forwardRef<
  React.ElementRef<typeof CheckboxPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>
>(({ className, ...props }, ref) => (
  <CheckboxPrimitive.Root
    ref={ref}
    className={cn(
      "peer h-5 w-5 shrink-0 rounded border-2 border-stone-300 shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-lavender)] focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-[var(--color-forest)] data-[state=checked]:text-white data-[state=checked]:border-[var(--color-forest)]",
      className
    )}
    {...props}
  >
    <CheckboxPrimitive.Indicator
      className={cn("flex items-center justify-center text-current")}
    >
      <CheckIcon className="h-4 w-4" />
    </CheckboxPrimitive.Indicator>
  </CheckboxPrimitive.Root>
))
Checkbox.displayName = CheckboxPrimitive.Root.displayName

export { Checkbox }
